import LocalizedStrings from 'react-localization';

export const _ = new LocalizedStrings({
    en: {
        title1: 'Red Team Operator',
        title2: 'Software Developer',
        introTitle: 'What is a red team operator?',
        intro: 'A red team operator is a cybersecurity expert who mimics real attacks on an organization\'s systems to uncover vulnerabilities.Unlike blue team defenders, they take on the role of adversaries, using advanced methods to find weaknesses.They function as ethical hackers, aiding organizations in fortifying their defenses by revealing security gaps before actual threats exploit them.',
        location: 'Munich, Germany',
        featured: 'Featured Achievements',
        certified: 'Certified',
        pentest: 'Penetration Testing',
        subcontractor: 'Subcontractor',
        loctime: 'Location / Time',
        title: 'Title',
        company: 'Company',
        contact: 'Contact',
        htbRanking: 'HTB Rank',
        htbRank: 'Guru',
        htbRankDetails: '2nd highest rank',
        htbTop: 'TOP 25',
        htbTopDetail: '2023, 22nd of 502 hackers',
        htbGlobal: 'HTB Global Ranking',
        htbGlobalRankSuffix: 'nd',
        htbDante: 'Dante',
        synackTitle: '9/10 points',
        synackSubtitle: 'Synack Red Teamer',
        synackDetails: 'Web & Host Attacks',
        zeropointTitle: 'Red Team Ops',
        zeropointDetails: 'Zero Point Security',
        turkGov: 'State Affairs',
        turkGovDetails: 'Government & Ministries',
        turkPolice: 'Homicide Department',
        turkOzel: 'Special Operations',
        portfolioTitle: 'Portfolio',
        portfolio: [
            'MOVEit Transfer Cyber Attack Research and Analysis',
            'Central Bank Digital Currencies (CBDC) + Ghana & Thailand Pilot Project',
            'WebGL, 3D, and VR customizers for the auto industry - Porsche, BMW, Audi, DS, Toyota, Hyundai',
            'Airbus Aircraft 3D Designer Software',
            'HDI Insurance Coach Assistant Software',
            'Chemondis - B2B Marketplace for Chemicals',
            'The World\'s First Mixed Reality TV Show',
            'Pharmaceutical Track and Trace System of Türkiye (ITS) subcontractor',
            'KYKNET Subcontractor / Türkiye\'s state-backed student loans and residences management system',
            'Türkiye Police Special Operation Department Subcontractor',
            'Turksat Tsunami - Cable Infrastructure Management Software',
            'Police Vehicle Chase Simulator with Hydraulic 6DOF',
            'Mobile Military Hospital Pilot Project',
            'Software Development for Türkiye Land Registry and Cadastre and The Grand National Assembly of Türkiye',
            'Türkiye\'s Automatic Criminal Denouncer in Hotel/Motel Entries',
            'Healthcare Applications with Kinect and Unity3D for Elderly',
            'PlayStation 1 Emulator for Intel Mobile Internet Devices',
            'Official Intel Success Story',
        ],
        workexpTitle: 'Work Experience',
        job: 'Title / Company',
        workexp: [
            {
                company: 'Schaeffler Group',
                companyInfo: 'A German manufacturer of rolling element bearings for automotive, aerospace and industrial uses',
                link: 'https://www.schaeffler.com/',
                job: 'Application Security Expert',
                start: '2023',
                end: '',
                location: 'Regensburg, Germany',
                flag: 'DE',
            },
            {
                company: 'Giesecke+Devrient',
                companyInfo: 'A German company headquartered in Munich that provides banknote and securities printing, smart cards, and cash handling systems',
                link: 'https://www.gi-de.com/',
                job: 'Cyber Security Expert',
                start: '2022',
                end: '2022',
                location: 'Munich, Germany',
                flag: 'DE',
            },
            {
                company: 'Synack',
                companyInfo: 'A crowdsourced network of white-hat hackers to find exploitable vulnerabilities and a SaaS platform enabled by AI and machine learning to identify exploitable vulnerabilities',
                link: 'https://www.synack.com/',
                job: 'Security Researcher',
                start: '2021',
                end: '2022',
                location: '(Remote), USA',
                flag: 'US',
            },
            {
                company: 'Dassault Systemes',
                companyInfo: 'A French multinational software corporation which develops software for 3D product design, simulation, manufacturing and other 3D related products',
                link: 'https://www.3ds.com/',
                job: 'Software Services Manager',
                start: '2019',
                end: '2022',
                location: 'Munich, Germany',
                flag: 'DE',
            },
            {
                company: 'KI Labs',
                companyInfo: 'Co-founding, angel-investing and building digital solutions for clients, up to building full-fledged companies',
                link: 'https://kigroup.de/',
                job: 'Technical Lead',
                start: '2017',
                end: '2019',
                location: 'Munich, Germany',
                flag: 'DE',
            },
            {
                company: 'Pixotope',
                companyInfo: 'In the business of democratizing virtual production and empowering content creators with our award-winning accessible solutions that enable boundary-pushing immersive storytelling',
                link: 'https://www.pixotope.com/',
                job: 'Senior Software Developer',
                start: '2017',
                end: '2017',
                location: 'Oslo, Norway',
                flag: 'NO',
            },
            {
                company: 'Podoces Technology',
                companyInfo: 'Software subcontractor of the projects from Turkish government, ministries and police departments',
                link: '',
                job: 'Founder & CEO',
                start: '2011',
                end: '2016',
                location: 'Ankara, Türkiye',
                flag: 'TR',
            },
            {
                company: 'Bilisim Inovasyon',
                companyInfo: 'Software contractor of the projects from Turkish ministries',
                link: '',
                job: 'Software Developer',
                start: '2009',
                end: '2012',
                location: 'Ankara, Türkiye',
                flag: 'TR',
            },
            {
                company: 'Intel',
                companyInfo: 'An American multinational corporation and technology company',
                link: 'https://www.intel.com/',
                job: 'Junior Software Developer',
                start: '2007',
                end: '2009',
                location: 'Ankara, Türkiye',
                flag: 'TR',
            },
        ],
        referencesTitle: 'References',
        reference: 'Reference / Contact',
        references: [
            {
                name: 'Martin Herrmann',
                title: 'Global CyberSec Team Lead',
                company: 'Schaeffler',
                contact: 'martin.herrmann@vitesco.com',
            },
            {
                name: 'Raoul Herborg',
                title: 'Managing Director',
                company: 'Giesecke+Devrient',
                contact: 'raoul.herborg@gi-de.com',
            },
            {
                name: 'Johannes Forster',
                title: 'CFO',
                company: 'Giesecke+Devrient',
                contact: 'johannes.forster@gi-de.com',
            },
            {
                name: 'Tobias Ilse',
                title: 'Sr. Manager',
                company: 'Dassault Systems',
                contact: 'tobias.ilse@3ds.com',
            },
            {
                name: 'Adem Ali Yilmaz',
                title: 'Managing Director',
                company: 'Tiga',
                contact: 'info@tiga.com.tr',
            }
        ],
        educationTitle: 'Education',
        institution: 'Institution',
        faculty: 'Faculty / Branch',
        education: [
            {
                name: 'Hacettepe University',
                dep: 'Bachelor of Science / Statistics',
                notes: 'Ankara, 2006 - 2016',
            },
            {
                name: 'Middle East Technical University',
                dep: 'Entrepreneurship',
                notes: 'Ankara, 2008',
            },
            {
                name: 'Ozyegin University',
                dep: 'Entrepreneurship',
                notes: 'Istanbul, 2007',
            },
        ],
        languagesTitle: 'Languages',
        languages: [
            {
                label: 'English',
                rank: "1",
            },
            {
                label: 'Turkish',
                rank: "0",
            },
            {
                label: 'German',
                rank: "3",
            }
        ],
        languageRanks: ["Native", "Fluent", "Intermediate", "Beginner",],
        privateTitle: 'Private Life',
        private: [
            'Super-sport motorcycle rider',
            'Camping and remote work with a fully equipped and online camper',
            'Cooking',
            'Open source experiments and contributions',
        ]
    },
    de: {
        title1: 'Red-Team-Operator',
        title2: 'Softwareentwickler',
        introTitle: 'Was ist ein Red-Team-Operator?',
        intro: 'Ein Red-Team-Operator ist ein Cybersecurity-Experte, der echte Angriffe auf die Systeme einer Organisation nachahmt, um Schwachstellen aufzudecken. Im Gegensatz zu Verteidigern des Blue Teams übernehmen sie die Rolle von Angreifern und verwenden fortgeschrittene Methoden, um Schwächen zu finden. Sie fungieren als ethische Hacker und helfen Organisationen, ihre Verteidigung zu stärken, indem sie Sicherheitslücken aufdecken, bevor tatsächliche Bedrohungen sie ausnutzen können.',
        location: 'München, Deutschland',
        featured: 'Hervorgehobene Erfolge',
        certified: 'Zertifiziert',
        pentest: 'Penetrationstests',
        subcontractor: 'Subunternehmer',
        loctime: 'Ort / Zeit',
        title: 'Titel',
        company: 'Unternehmen',
        contact: 'Kontakt',
        htbRanking: 'HTB-Rang',
        htbRank: 'Guru',
        htbRankDetails: 'Zweitbester Rang',
        htbTop: 'TOP 25',
        htbTopDetail: '2023, 22. von 502 Hackern',
        htbGlobal: 'HTB-Weltrangliste',
        htbGlobalRankSuffix: '.',
        htbDante: 'Dante',
        synackTitle: '9/10 Punkte',
        synackSubtitle: 'Synack-Red-Teamer',
        synackDetails: 'Web- & Host-Angriffe',
        zeropointTitle: 'Red-Team-Ops',
        zeropointDetails: 'Zero-Point-Sicherheit',
        turkGov: 'Staatsangelegenheiten',
        turkGovDetails: 'Regierung & Ministerien',
        turkPolice: 'Mordkommission',
        turkOzel: 'Sondereinsätze',
        portfolioTitle: 'Portfolio',
        portfolio: [
            'MOVEit Transfer Cyber-Angriffs-Forschung und -Analyse',
            'Zentralbank-Digitale Währungen (CBDC) + Pilotprojekt Ghana & Thailand',
            'WebGL-, 3D- und VR-Anpasser für die Automobilindustrie - Porsche, BMW, Audi, DS, Toyota, Hyundai',
            'Airbus Flugzeug 3D-Designer-Software',
            'HDI Versicherungs-Coach-Assistenten-Software',
            'Chemondis - B2B-Marktplatz für Chemikalien',
            'Die weltweit erste Mixed-Reality-TV-Show',
            'Pharmazeutisches Track- und Trace-System der Türkei (ITS) als Subunternehmer',
            'KYKNET-Subunternehmer / Türkei\'s staatlich unterstütztes Studentendarlehen und Wohnanlagen-Management-System',
            'Türkische Polizei-Sondereinsatzabteilung als Subunternehmer',
            'Turksat Tsunami - Kabelinfrastruktur-Management-Software',
            'Polizeifahrzeug-Verfolgungssimulator mit hydraulischem 6DOF',
            'Mobiles Militärkrankenhaus-Pilotprojekt',
            'Softwareentwicklung für das Türkische Grundbuchamt und das Parlament der Türkei',
            'Türkei\'s Automatischer Krimindenunzierer bei Hotel/Motel-Eintritten',
            'Gesundheitsanwendungen mit Kinect und Unity3D für Senioren',
            'PlayStation 1 Emulator für Intel Mobile Internet Devices',
            'Offizielle Intel-Erfolgsgeschichte',
        ],
        workexpTitle: 'Berufserfahrung',
        job: 'Titel / Unternehmen',
        workexp: [
            {
                company: 'Schaeffler Group',
                companyInfo: 'Ein deutscher Hersteller von Wälzlagern für die Automobil-, Luft- und Raumfahrt- und Industrieanwendungen',
                link: 'https://www.schaeffler.com/',
                job: 'Anwendungssicherheits-Experte',
                start: '2023',
                end: '',
                location: 'Regensburg, Deutschland',
                flag: 'DE',
            },
            {
                company: 'Giesecke+Devrient',
                companyInfo: 'Ein in München ansässiges deutsches Unternehmen, das Banknoten- und Wertpapierdruck, Smartcards und Bargeldverarbeitungssysteme anbietet',
                link: 'https://www.gi-de.com/',
                job: 'Cyber-Sicherheitsexperte',
                start: '2022',
                end: '2022',
                location: 'München, Deutschland',
                flag: 'DE',
            },
            {
                company: 'Synack',
                companyInfo: 'Ein Netzwerk von White-Hat-Hackern, um ausnutzbare Schwachstellen zu finden, und eine KI- und maschinenlernfähige SaaS-Plattform zur Identifizierung ausnutzbarer Schwachstellen',
                link: 'https://www.synack.com/',
                job: 'Sicherheitsforscher',
                start: '2021',
                end: '2022',
                location: '(Remote), USA',
                flag: 'US',
            },
            {
                company: 'Dassault Systemes',
                companyInfo: 'Ein französisches multinationales Softwareunternehmen, das Software für 3D-Produktdesign, Simulation, Fertigung und andere 3D-bezogene Produkte entwickelt',
                link: 'https://www.3ds.com/',
                job: 'Manager für Software-Services',
                start: '2019',
                end: '2022',
                location: 'München, Deutschland',
                flag: 'DE',
            },
            {
                company: 'KI Labs',
                companyInfo: 'Mitgründung, Angel-Investing und Aufbau digitaler Lösungen für Kunden, bis hin zum Aufbau vollwertiger Unternehmen',
                link: 'https://kigroup.de/',
                job: 'Technischer Leiter',
                start: '2017',
                end: '2019',
                location: 'München, Deutschland',
                flag: 'DE',
            },
            {
                company: 'Pixotope',
                companyInfo: 'Im Geschäft mit der Demokratisierung der virtuellen Produktion und der Ermächtigung von Inhalten mit unseren preisgekrönten zugänglichen Lösungen, die grenzüberschreitendes immersives Storytelling ermöglichen',
                link: 'https://www.pixotope.com/',
                job: 'Senior-Softwareentwickler',
                start: '2017',
                end: '2017',
                location: 'Oslo, Norwegen',
                flag: 'NO',
            },
            {
                company: 'Podoces Technology',
                companyInfo: 'Software-Subunternehmer für Projekte der türkischen Regierung, Ministerien und Polizeibehörden',
                link: '',
                job: 'Gründer & CEO',
                start: '2011',
                end: '2016',
                location: 'Ankara, Türkei',
                flag: 'TR',
            },
            {
                company: 'Bilisim Inovasyon',
                companyInfo: 'Software-Vertragspartner für Projekte der türkischen Ministerien',
                link: '',
                job: 'Softwareentwickler',
                start: '2009',
                end: '2012',
                location: 'Ankara, Türkei',
                flag: 'TR',
            },
            {
                company: 'Intel',
                companyInfo: 'Ein amerikanisches multinationales Technologieunternehmen',
                link: 'https://www.intel.com/',
                job: 'Junior-Softwareentwickler',
                start: '2007',
                end: '2009',
                location: 'Ankara, Türkei',
                flag: 'TR',
            },
        ],
        referencesTitle: 'Referenzen',
        reference: 'Referenz / Kontakt',
        references: [
            {
                name: 'Martin Herrmann',
                title: 'Leiter des globalen CyberSec-Teams',
                company: 'Schaeffler',
                contact: 'martin.herrmann@vitesco.com',
            },
            {
                name: 'Raoul Herborg',
                title: 'Geschäftsführer',
                company: 'Giesecke+Devrient',
                contact: 'raoul.herborg@gi-de.com',
            },
            {
                name: 'Johannes Forster',
                title: 'CFO',
                company: 'Giesecke+Devrient',
                contact: 'johannes.forster@gi-de.com',
            },
            {
                name: 'Tobias Ilse',
                title: 'Sr. Manager',
                company: 'Dassault Systems',
                contact: 'tobias.ilse@3ds.com',
            },
            {
                name: 'Adem Ali Yilmaz',
                title: 'Geschäftsführer',
                company: 'Tiga',
                contact: 'info@tiga.com.tr',
            }
        ],
        educationTitle: 'Bildung',
        institution: 'Institution',
        faculty: 'Fakultät / Fachrichtung',
        education: [
            {
                name: 'Hacettepe-Universität',
                dep: 'Bachelor of Science / Statistik',
                notes: 'Ankara, 2006 - 2016',
            },
            {
                name: 'Technische Universität des Nahen Ostens',
                dep: 'Unternehmertum',
                notes: 'Ankara, 2008',
            },
            {
                name: 'Ozyegin-Universität',
                dep: 'Unternehmertum',
                notes: 'Istanbul, 2007',
            },
        ],
        languagesTitle: 'Sprachen',
        languages: [
            {
                label: 'Englisch',
                rank: "1",
            },
            {
                label: 'Türkisch',
                rank: "0",
            },
            {
                label: 'Deutsch',
                rank: "3",
            }
        ],
        languageRanks: ["Muttersprachler", "Fließend", "Mittelstufe", "Anfänger",],
        privateTitle: 'Privatleben',
        private: [
            'Hochleistungsmotorradfahrer',
            'Camping und Remote-Arbeit mit einem voll ausgestatteten und online-vernetzten Wohnmobil',
            'Kochen',
            'Experimente und Beiträge im Open Source-Bereich',
        ]
    },
    tr: {
        title1: 'Kırmızı Takım Operatörü',
        title2: 'Yazılım Geliştirici',
        introTitle: 'Kırmızı takım operatörü nedir?',
        intro: 'Kırmızı takım operatörü, bir kuruluşun sistemlerinde gerçek saldırıları taklit ederek zayıflıkları ortaya çıkaran bir siber güvenlik uzmanıdır. Mavi takım savunucularının aksine, düşmanların rolünü üstlenirler, ileri yöntemler kullanarak zayıflıkları bulurlar. Etik hackerlar olarak işlev görerek, gerçek tehditlerin bunları sömürmeden önce güvenlik boşluklarını ortaya çıkararak kuruluşlara savunmalarını güçlendirmelerine yardımcı olurlar.',
        location: 'Münih, Almanya',
        featured: 'Öne Çıkan Başarılar',
        certified: 'Sertifikalı',
        pentest: 'Sızma Testi',
        subcontractor: 'Taşeron',
        loctime: 'Konum / Zaman',
        title: 'Başlık',
        company: 'Şirket',
        contact: 'İletişim',
        htbRanking: 'HTB Sıralaması',
        htbRank: 'Uzman',
        htbRankDetails: '2. en yüksek sıralama',
        htbTop: 'EN İYİ 25',
        htbTopDetail: '2023, 502 hacker içinde 22.',
        htbGlobal: 'HTB Küresel Sıralama',
        htbGlobalRankSuffix: '.',
        htbDante: 'Dante',
        synackTitle: '9/10 puan',
        synackSubtitle: 'Synack Kırmızı Takım Üyesi',
        synackDetails: 'Web & Host Saldırıları',
        zeropointTitle: 'Kırmızı Takım Operasyonları',
        zeropointDetails: 'Sıfır Nokta Güvenliği',
        turkGov: 'Devlet İşleri',
        turkGovDetails: 'Hükümet ve Bakanlıklar',
        turkPolice: 'Cinayet Bürosu',
        turkOzel: 'Özel Operasyonlar',
        portfolioTitle: 'Portföy',
        portfolio: [
            'MOVEit Transfer Siber Saldırı Araştırması ve Analizi',
            'Merkez Bankası Dijital Paraları (CBDC) + Gana ve Tayland Pilot Projesi',
            'Otomotiv endüstrisi için WebGL, 3D ve VR özelleştiricileri - Porsche, BMW, Audi, DS, Toyota, Hyundai',
            'Airbus Uçak 3D Tasarımcı Yazılımı',
            'HDI Sigorta Koç Asistan Yazılımı',
            'Chemondis - Kimyasallar için B2B Pazar Yeri',
            'Dünyanın İlk Karma Gerçeklik TV Programı',
            'Türkiye\'nin İlaç Takip ve İzleme Sistemi(ITS) taşeronu',
            'KYKNET Taşeronu / Türkiye\'nin devlet destekli öğrenci kredileri ve konut yönetim sistemi',
            'Türkiye Polis Özel Operasyonlar Dairesi Taşeronu',
            'Turksat Tsunami - Kablo Altyapı Yönetim Yazılımı',
            'Polis Araç Takip Simülatörü Hidrolik 6DOF ile',
            'Mobil Askeri Hastane Pilot Projesi',
            'Türkiye Tapu ve Kadastro ve Türkiye Büyük Millet Meclisi için Yazılım Geliştirme',
            'Türkiye\'nin Otomatik Suç Bildirici Oteli / Motel Girişleri',
            'Yaşlılar için Kinect ve Unity3D ile Sağlık Uygulamaları',
            'Intel Mobil İnternet Cihazları için PlayStation 1 Emülatörü',
            'Resmi Intel Başarı Hikayesi',
        ],
        workexpTitle: 'İş Deneyimi',
        job: 'Unvan / Şirket',
        workexp: [
            {
                company: 'Schaeffler Grubu',
                companyInfo: 'Otomotiv, havacılık ve endüstriyel kullanımlar için silindirik rulman üreticisi Alman şirketi',
                link: 'https://www.schaeffler.com/',
                job: 'Uygulama Güvenliği Uzmanı',
                start: '2023',
                end: '',
                location: 'Regensburg, Almanya',
                flag: 'DE',
            },
            {
                company: 'Giesecke+Devrient',
                companyInfo: 'Münih merkezli Alman şirketi, banknot ve menkul kıymet basımı, akıllı kartlar ve nakit işleme sistemleri sağlar',
                link: 'https://www.gi-de.com/',
                job: 'Siber Güvenlik Uzmanı',
                start: '2022',
                end: '2022',
                location: 'Münih, Almanya',
                flag: 'DE',
            },
            {
                company: 'Synack',
                companyInfo: 'Siber saldırılara karşı korunaklı zayıflıkları bulmak için beyaz şapkalı hackerların işbirliği ağı ve AI ve makine öğrenimi tarafından etkinleştirilen bir SaaS platformu',
                link: 'https://www.synack.com/',
                job: 'Güvenlik Araştırmacısı',
                start: '2021',
                end: '2022',
                location: '(Uzaktan), ABD',
                flag: 'US',
            },
            {
                company: 'Dassault Systèmes',
                companyInfo: '3D ürün tasarımı, simülasyon, imalat ve diğer 3D ile ilgili ürünler için yazılım geliştiren Fransız çok uluslu yazılım şirketi',
                link: 'https://www.3ds.com/',
                job: 'Yazılım Hizmetleri Yöneticisi',
                start: '2019',
                end: '2022',
                location: 'Münih, Almanya',
                flag: 'DE',
            },
            {
                company: 'KI Labs',
                companyInfo: 'Müşteriler için dijital çözümler inşa etme ve tam teşekküllü şirketler oluşturma konusunda ortaklık, melek yatırım ve yapılandırma',
                link: 'https://kigroup.de/',
                job: 'Teknik Lider',
                start: '2017',
                end: '2019',
                location: 'Münih, Almanya',
                flag: 'DE',
            },
            {
                company: 'Pixotope',
                companyInfo: 'Sanal prodüksiyonu demokratikleştirmek ve sınırları zorlayan içerik üreticilerine ödüllü erişilebilir çözümlerimizle anlatıyı zenginleştirmek',
                link: 'https://www.pixotope.com/',
                job: 'Kıdemli Yazılım Geliştirici',
                start: '2017',
                end: '2017',
                location: 'Oslo, Norveç',
                flag: 'NO',
            },
            {
                company: 'Podoces Technology',
                companyInfo: 'Türk hükümeti, bakanlıkları ve polis departmanlarından projelerin yazılım taşeronu',
                link: '',
                job: 'Kurucu & CEO',
                start: '2011',
                end: '2016',
                location: 'Ankara, Türkiye',
                flag: 'TR',
            },
            {
                company: 'Bilisim Inovasyon',
                companyInfo: 'Türk bakanlıklarından projelerin yazılım yüklenicisi',
                link: '',
                job: 'Yazılım Geliştirici',
                start: '2009',
                end: '2012',
                location: 'Ankara, Türkiye',
                flag: 'TR',
            },
            {
                company: 'Intel',
                companyInfo: 'Amerikan çok uluslu bir teknoloji şirketi',
                link: 'https://www.intel.com/',
                job: 'Genç Yazılım Geliştirici',
                start: '2007',
                end: '2009',
                location: 'Ankara, Türkiye',
                flag: 'TR',
            },
        ],
        referencesTitle: 'Referanslar',
        reference: 'Referans / İletişim',
        references: [
            {
                name: 'Martin Herrmann',
                title: 'Küresel Siber Güvenlik Takım Lideri',
                company: 'Schaeffler',
                contact: 'martin.herrmann@vitesco.com',
            },
            {
                name: 'Raoul Herborg',
                title: 'Genel Müdür',
                company: 'Giesecke+Devrient',
                contact: 'raoul.herborg@gi-de.com',
            },
            {
                name: 'Johannes Forster',
                title: 'CFO',
                company: 'Giesecke+Devrient',
                contact: 'johannes.forster@gi-de.com',
            },
            {
                name: 'Tobias Ilse',
                title: 'Kıdemli Müdür',
                company: 'Dassault Systems',
                contact: 'tobias.ilse@3ds.com',
            },
            {
                name: 'Adem Ali Yılmaz',
                title: 'Genel Müdür',
                company: 'Tiga',
                contact: 'info@tiga.com.tr',
            }
        ],
        educationTitle: 'Eğitim',
        institution: 'Kurum',
        faculty: 'Fakülte / Branş',
        education: [
            {
                name: 'Hacettepe Üniversitesi',
                dep: 'Lisans / İstatistik',
                notes: 'Ankara, 2006 - 2016',
            },
            {
                name: 'Orta Doğu Teknik Üniversitesi',
                dep: 'Girişimcilik',
                notes: 'Ankara, 2008',
            },
            {
                name: 'Özyeğin Üniversitesi',
                dep: 'Girişimcilik',
                notes: 'İstanbul, 2007',
            },
        ],
        languagesTitle: 'Diller',
        languages: [
            {
                label: 'İngilizce',
                rank: "1",
            },
            {
                label: 'Türkçe',
                rank: "0",
            },
            {
                label: 'Almanca',
                rank: "3",
            }
        ],
        languageRanks: ["Ana Dil", "Akıcı", "Orta", "Başlangıç",],
        privateTitle: 'Özel Hayat',
        private: [
            'Süper spor motosiklet sürücüsü',
            'Tam donanımlı ve çevrimiçi bir karavanla kamp yapma ve uzaktan çalışma',
            'Yemek pişirme',
            'Açık kaynak deneyleri ve katkıları',
        ]
    },
    it: {
        title1: 'Operatore del Team Rosso',
        title2: 'Sviluppatore Software',
        introTitle: 'Cosa è un operatore del team rosso?',
        intro: 'Un operatore del team rosso è un esperto di sicurezza informatica che simula veri attacchi ai sistemi di un\'organizzazione per scoprire vulnerabilità. A differenza dei difensori del team blu, assumono il ruolo degli avversari, utilizzando metodi avanzati per trovare debolezze. Agiscono come hacker etici, aiutando le organizzazioni a rafforzare le loro difese rivelando lacune di sicurezza prima che minacce effettive le sfruttino.',
        location: 'Monaco di Baviera, Germania',
        featured: 'Successi in evidenza',
        certified: 'Certificato',
        pentest: 'Test di penetrazione',
        subcontractor: 'Subappaltatore',
        loctime: 'Luogo / Orario',
        title: 'Titolo',
        company: 'Azienda',
        contact: 'Contatto',
        htbRanking: 'Classifica HTB',
        htbRank: 'Guru',
        htbRankDetails: 'Secondo posto',
        htbTop: 'TOP 25',
        htbTopDetail: '2023, 22° su 502 hacker',
        htbGlobal: 'Classifica globale HTB',
        htbGlobalRankSuffix: 'nd',
        htbDante: 'Dante',
        synackTitle: '9/10 punti',
        synackSubtitle: 'Membro del team rosso di Synack',
        synackDetails: 'Attacchi Web & Host',
        zeropointTitle: 'Operazioni del Team Rosso',
        zeropointDetails: 'Sicurezza Zero Point',
        turkGov: 'Affari di Stato',
        turkGovDetails: 'Governo e Ministeri',
        turkPolice: 'Reparto Omicidi',
        turkOzel: 'Operazioni Speciali',
        portfolioTitle: 'Portfolio',
        portfolio: [
            'Ricerca e analisi degli attacchi informatici su MOVEit Transfer',
            'Valuta Digitale delle Banche Centrali (CBDC) + Progetto pilota in Ghana e Thailandia',
            'Personalizzatori WebGL, 3D e VR per l\'industria automobilistica - Porsche, BMW, Audi, DS, Toyota, Hyundai',
            'Software designer 3D per aeromobili Airbus',
            'Software assistente per coach assicurativi HDI',
            'Chemondis - Marketplace B2B per Prodotti Chimici',
            'La prima trasmissione televisiva in Realtà Mista al mondo',
            'Subappaltatore per il Sistema di Tracciamento Farmaceutico di Türkiye (ITS)',
            'Subappaltatore per KYKNET / Sistema di gestione dei prestiti agli studenti e delle residenze supportato dallo stato di Türkiye',
            'Subappaltatore del Dipartimento di Operazioni Speciali della Polizia di Türkiye',
            'Turksat Tsunami - Software per la gestione dell\'infrastruttura via cavo',
            'Simulatore di inseguimento veicoli della polizia con 6DOF idraulico',
            'Progetto pilota di ospedale militare mobile',
            'Sviluppo software per il Catasto e il Parlamento di Türkiye',
            'Denunciatore automatico dei criminali di Türkiye negli alberghi/motel',
            'Applicazioni sanitarie con Kinect e Unity3D per anziani',
            'Emulatore PlayStation 1 per dispositivi mobili Intel',
            'Storia di successo ufficiale di Intel',
        ],
        workexpTitle: 'Esperienza lavorativa',
        job: 'Titolo / Azienda',
        workexp: [
            {
                company: 'Schaeffler Group',
                companyInfo: 'Produttore tedesco di cuscinetti a rulli per applicazioni automobilistiche, aerospaziali e industriali',
                link: 'https://www.schaeffler.com/',
                job: 'Esperto in sicurezza delle applicazioni',
                start: '2023',
                end: '',
                location: 'Ratisbona, Germania',
                flag: 'DE',
            },
            {
                company: 'Giesecke+Devrient',
                companyInfo: 'Azienda tedesca con sede a Monaco che fornisce stampa di banconote e titoli di stato, smart card e sistemi di gestione del contante',
                link: 'https://www.gi-de.com/',
                job: 'Esperto di sicurezza informatica',
                start: '2022',
                end: '2022',
                location: 'Monaco di Baviera, Germania',
                flag: 'DE',
            },
            {
                company: 'Synack',
                companyInfo: 'Rete collaborativa di hacker white-hat per individuare vulnerabilità sfruttabili e una piattaforma SaaS abilitata da AI e machine learning per identificare vulnerabilità sfruttabili',
                link: 'https://www.synack.com/',
                job: 'Ricercatore di sicurezza',
                start: '2021',
                end: '2022',
                location: '(Remoto), USA',
                flag: 'US',
            },
            {
                company: 'Dassault Systemes',
                companyInfo: 'Multinazionale francese che sviluppa software per la progettazione di prodotti 3D, simulazione, produzione e altri prodotti correlati al 3D',
                link: 'https://www.3ds.com/',
                job: 'Responsabile dei servizi software',
                start: '2019',
                end: '2022',
                location: 'Monaco di Baviera, Germania',
                flag: 'DE',
            },
            {
                company: 'KI Labs',
                companyInfo: 'Co-fondazione, investimenti angelici e sviluppo di soluzioni digitali per clienti, fino alla creazione di aziende complete',
                link: 'https://kigroup.de/',
                job: 'Responsabile tecnico',
                start: '2017',
                end: '2019',
                location: 'Monaco di Baviera, Germania',
                flag: 'DE',
            },
            {
                company: 'Pixotope',
                companyInfo: 'Nel settore della democratizzazione della produzione virtuale e dell\'empowerment dei creatori di contenuti con le nostre soluzioni premiate e accessibili che consentono la narrazione immersiva',
                link: 'https://www.pixotope.com/',
                job: 'Sviluppatore software senior',
                start: '2017',
                end: '2017',
                location: 'Oslo, Norvegia',
                flag: 'NO',
            },
            {
                company: 'Podoces Technology',
                companyInfo: 'Subappaltatore di software dei progetti del governo turco, ministeri e dipartimenti di polizia',
                link: '',
                job: 'Fondatore & CEO',
                start: '2011',
                end: '2016',
                location: 'Ankara, Türkiye',
                flag: 'TR',
            },
            {
                company: 'Bilisim Inovasyon',
                companyInfo: 'Appaltatore di software dei progetti dei ministeri turchi',
                link: '',
                job: 'Sviluppatore software',
                start: '2009',
                end: '2012',
                location: 'Ankara, Türkiye',
                flag: 'TR',
            },
            {
                company: 'Intel',
                companyInfo: 'Multinazionale americana e società tecnologica',
                link: 'https://www.intel.com/',
                job: 'Junior sviluppatore software',
                start: '2007',
                end: '2009',
                location: 'Ankara, Türkiye',
                flag: 'TR',
            },
        ],
        referencesTitle: 'Referenze',
        reference: 'Riferimento / Contatto',
        references: [
            {
                name: 'Martin Herrmann',
                title: 'Responsabile del team CyberSec globale',
                company: 'Schaeffler',
                contact: 'martin.herrmann@vitesco.com',
            },
            {
                name: 'Raoul Herborg',
                title: 'Direttore generale',
                company: 'Giesecke+Devrient',
                contact: 'raoul.herborg@gi-de.com',
            },
            {
                name: 'Johannes Forster',
                title: 'CFO',
                company: 'Giesecke+Devrient',
                contact: 'johannes.forster@gi-de.com',
            },
            {
                name: 'Tobias Ilse',
                title: 'Sr. Manager',
                company: 'Dassault Systems',
                contact: 'tobias.ilse@3ds.com',
            },
            {
                name: 'Adem Ali Yilmaz',
                title: 'Direttore generale',
                company: 'Tiga',
                contact: 'info@tiga.com.tr',
            }
        ],
        educationTitle: 'Educazione',
        institution: 'Istituzione',
        faculty: 'Facoltà / Ramo',
        education: [
            {
                name: 'Università Hacettepe',
                dep: 'Laurea in Scienze / Statistica',
                notes: 'Ankara, 2006 - 2016',
            },
            {
                name: 'Università Tecnica del Medio Oriente',
                dep: 'Imprenditorialità',
                notes: 'Ankara, 2008',
            },
            {
                name: 'Università Ozyegin',
                dep: 'Imprenditorialità',
                notes: 'Istanbul, 2007',
            },
        ],
        languagesTitle: 'Lingue',
        languages: [
            {
                label: 'Inglese',
                rank: "1",
            },
            {
                label: 'Turco',
                rank: "0",
            },
            {
                label: 'Tedesco',
                rank: "3",
            }
        ],
        languageRanks: ["Madrelingua", "Fluente", "Intermedio", "Principiante",],
        privateTitle: 'Vita privata',
        private: [
            'Motociclista super sportivo',
            'Campeggio e lavoro remoto con un camper completamente attrezzato e online',
            'Cucinare',
            'Esperimenti e contributi open source',
        ]
    },
    gr: {
        title1: 'Τεχνικός Ομάδας Ερυθράς',
        title2: 'Προγραμματιστής Λογισμικού',
        introTitle: 'Τι είναι ένας τεχνικός ομάδας ερυθράς;',
        intro: 'Ένας τεχνικός ομάδας ερυθράς είναι ένας ειδικός στην κυβερνοασφάλεια που μιμείται πραγματικές επιθέσεις στα συστήματα μιας οργάνωσης για να ανακαλύψει ευπάθειες. Αντίθετα από τους αμυντικούς της μπλε ομάδας, αναλαμβάνουν τον ρόλο των αντιπάλων, χρησιμοποιώντας προηγμένες μεθόδους για να βρουν αδυναμίες. Λειτουργούν ως ηθικοί χάκερς, βοηθώντας τις οργανώσεις να ενισχύσουν τις προστατευτικές τους δομές αποκαλύπτοντας τις ασφαλειακές τους κενές πριν από πραγματικές απειλές να τις εκμεταλλευτούν.',
        location: 'Μόναχο, Γερμανία',
        featured: 'Εξαιρετικά Επιτεύγματα',
        certified: 'Πιστοποιημένος',
        pentest: 'Δοκιμή Διείσδυσης',
        subcontractor: 'Υποεργολάβος',
        loctime: 'Τοποθεσία / Χρόνος',
        title: 'Τίτλος',
        company: 'Εταιρεία',
        contact: 'Επικοινωνία',
        htbRanking: 'Βαθμολογία HTB',
        htbRank: 'Ειδικός',
        htbRankDetails: '2η υψηλότερη βαθμολογία',
        htbTop: 'ΚΟΡΥΦΗ 25',
        htbTopDetail: '2023, 22ος από 502 χάκερς',
        htbGlobal: 'Παγκόσμια Βαθμολογία HTB',
        htbGlobalRankSuffix: 'ος',
        htbDante: 'Ντάντε',
        synackTitle: '9/10 βαθμοί',
        synackSubtitle: 'Μέλος της Ομάδας Ερυθράς της Synack',
        synackDetails: 'Επιθέσεις στον Ιστό & τον Φιλοξενητή',
        zeropointTitle: 'Λειτουργίες Ομάδας Ερυθράς',
        zeropointDetails: 'Ασφάλεια Μηδενικού Σημείου',
        turkGov: 'Υποθέσεις Κράτους',
        turkGovDetails: 'Κυβέρνηση & Υπουργεία',
        turkPolice: 'Τμήμα Εγκλημάτων',
        turkOzel: 'Ειδικές Επιχειρήσεις',
        portfolioTitle: 'Πορτφόλιο',
        portfolio: [
            'Έρευνα και Ανάλυση Κυβερνετικής Επίθεσης στην Μεταφορά MOVEit',
            'Ψηφιακά Νομίσματα της Κεντρικής Τράπεζας (CBDC) + Πιλοτικό Έργο στη Γκάνα και την Ταϊλάνδη',
            'Προσαρμοσμένοι εξομοιωτές WebGL, 3D και VR για τη βιομηχανία αυτοκινήτων - Porsche, BMW, Audi, DS, Toyota, Hyundai',
            'Λογισμικό Σχεδιασμού 3D για Αεροσκάφη Airbus',
            'Λογισμικό Βοηθού Προπονητής της Ασφαλιστικής HDI',
            'Chemondis - Εμπορική Πλατφόρμα για Χημικά Προϊόντα B2B',
            'Το Πρώτο Μικτό Πραγματικότητας Τηλεοπτικό Πρόγραμμα στον Κόσμο',
            'Υποεργολάβος του Συστήματος Ανίχνευσης και Εντοπισμού Φαρμακευτικών της Τουρκίας (ITS)',
            'Υποεργολάβος του ΚΥΚΝΕΤ / Σύστημα Διαχείρισης Φοιτητικών Δανείων και Κατοικιών της Τουρκίας',
            'Υποεργολάβος του Τμήματος Ειδικών Επιχειρήσεων της Τουρκικής Αστυνομίας',
            'Λογισμικό Διαχείρισης Υποδομών Καλωδίων Turksat Tsunami',
            'Προσομοίωση Καταδίωξης Αστυνομικών Οχημάτων με Υδραυλικό 6DOF',
            'Πιλοτικό Έργο για Κινητό Στρατιωτικό Νοσοκομείο',
            'Ανάπτυξη Λογισμικού για το Κτηματολόγιο και την Καταστολή Τουρκίας και τη Μεγάλη Εθνοσυνέλευση της Τουρκίας',
            'Αυτόματος Αναγνώστης Εγκλημάτων της Τουρκίας στις Εισόδους Ξενοδοχείων/Μοτέλ',
            'Εφαρμογές Φροντίδας Υγείας με Kinect και Unity3D για τους Ηλικιωμένους',
            'Εξομοιωτής PlayStation 1 για Συσκευές Κινητού Διαδικτύου Intel',
            'Επίσημη Ιστορία Επιτυχίας της Intel',
        ],
        workexpTitle: 'Επαγγελματική Εμπειρία',
        job: 'Τίτλος / Εταιρεία',
        workexp: [
            {
                company: 'Ομάδα Schaeffler',
                companyInfo: 'Γερμανική εταιρεία κατασκευής κυλινδρικών ρουλεμάν για αυτοκινητικές, αεροδιαστημικές και βιομηχανικές χρήσεις',
                link: 'https://www.schaeffler.com/',
                job: 'Ειδικός Ασφάλειας Εφαρμογών',
                start: '2023',
                end: '',
                location: 'Ρέγκενσμπουργκ, Γερμανία',
                flag: 'DE',
            },
            {
                company: 'Giesecke+Devrient',
                companyInfo: 'Γερμανική εταιρεία με έδρα τη Μόναχο που παρέχει εκτύπωση χαρτονομισμάτων και αξιώσεων, έξυπνες κάρτες και συστήματα χειρισμού μετρητών',
                link: 'https://www.gi-de.com/',
                job: 'Ειδικός Κυβερνοασφάλειας',
                start: '2022',
                end: '2022',
                location: 'Μόναχο, Γερμανία',
                flag: 'DE',
            },
            {
                company: 'Synack',
                companyInfo: 'Δίκτυο συνεργασίας λευκών χακέρ για την εύρεση ευπάθειων που μπορούν να εκμεταλλευτούν σε κυβερνοεπιθέσεις και πλατφόρμα SaaS που ενεργοποιείται από AI και μηχανική μάθηση',
                link: 'https://www.synack.com/',
                job: 'Ερευνητής Ασφάλειας',
                start: '2021',
                end: '2022',
                location: '(Απομακρυσμένη), ΗΠΑ',
                flag: 'US',
            },
            {
                company: 'Dassault Systèmes',
                companyInfo: 'Γαλλική πολυεθνική εταιρεία λογισμικού που αναπτύσσει λογισμικό για τον σχεδιασμό 3D προϊόντων, προσομοίωση, κατασκευή και άλλα σχετικά προϊόντα 3D',
                link: 'https://www.3ds.com/',
                job: 'Διευθυντής Υπηρεσιών Λογισμικού',
                start: '2019',
                end: '2022',
                location: 'Μόναχο, Γερμανία',
                flag: 'DE',
            },
            {
                company: 'KI Labs',
                companyInfo: 'Συνιδιοκτησία, αγγελιοδότηση και δημιουργία ψηφιακών λύσεων για πελάτες, μέχρι τη δημιουργία πλήρων εταιριών',
                link: 'https://kigroup.de/',
                job: 'Τεχνικός Αρχηγός',
                start: '2017',
                end: '2019',
                location: 'Μόναχο, Γερμανία',
                flag: 'DE',
            },
            {
                company: 'Pixotope',
                companyInfo: 'Στον τομέα της δημοκρατοποίησης της εικονικής παραγωγής και της ενδυνάμωσης των δημιουργών περιεχομένου με τις βραβευμένες μας προσβάσιμες λύσεις που επιτρέπουν την προώθηση της αφήγησης με πλούσιο περιεχόμενο',
                link: 'https://www.pixotope.com/',
                job: 'Κύριος Προγραμματιστής Λογισμικού',
                start: '2017',
                end: '2017',
                location: 'Όσλο, Νορβηγία',
                flag: 'NO',
            },
            {
                company: 'Podoces Technology',
                companyInfo: 'Υποεργολάβος λογισμικού των έργων από την τουρκική κυβέρνηση, υπουργεία και τμήματα αστυνομίας',
                link: '',
                job: 'Ιδρυτής & CEO',
                start: '2011',
                end: '2016',
                location: 'Άγκυρα, Τουρκία',
                flag: 'TR',
            },
            {
                company: 'Bilisim Inovasyon',
                companyInfo: 'Εργολάβος λογισμικού των έργων από τα τουρκικά υπουργεία',
                link: '',
                job: 'Προγραμματιστής Λογισμικού',
                start: '2009',
                end: '2012',
                location: 'Άγκυρα, Τουρκία',
                flag: 'TR',
            },
            {
                company: 'Intel',
                companyInfo: 'Αμερικανική πολυεθνική εταιρεία και εταιρεία τεχνολογίας',
                link: 'https://www.intel.com/',
                job: 'Νεαρός Προγραμματιστής Λογισμικού',
                start: '2007',
                end: '2009',
                location: 'Άγκυρα, Τουρκία',
                flag: 'TR',
            },
        ],
        referencesTitle: 'Αναφορές',
        reference: 'Αναφορά / Επικοινωνία',
        references: [
            {
                name: 'Martin Herrmann',
                title: 'Παγκόσμιος Αρχηγός Ομάδας CyberSec',
                company: 'Schaeffler',
                contact: 'martin.herrmann@vitesco.com',
            },
            {
                name: 'Raoul Herborg',
                title: 'Διευθυντής Εκτελεστικού Συμβουλίου',
                company: 'Giesecke+Devrient',
                contact: 'raoul.herborg@gi-de.com',
            },
            {
                name: 'Johannes Forster',
                title: 'Διευθυντής Οικονομικών',
                company: 'Giesecke+Devrient',
                contact: 'johannes.forster@gi-de.com',
            },
            {
                name: 'Tobias Ilse',
                title: 'Διευθυντής',
                company: 'Dassault Systems',
                contact: 'tobias.ilse@3ds.com',
            },
            {
                name: 'Adem Ali Yilmaz',
                title: 'Διευθυντής Εκτελεστικού Συμβούλου',
                company: 'Tiga',
                contact: 'info@tiga.com.tr',
            }
        ],
        educationTitle: 'Εκπαίδευση',
        institution: 'Ίδρυμα',
        faculty: 'Τμήμα / Κλάδος',
        education: [
            {
                name: 'Πανεπιστήμιο Χατσέτεπε',
                dep: 'Πτυχίο Επιστήμης / Στατιστική',
                notes: 'Άγκυρα, 2006 - 2016',
            },
            {
                name: 'Τεχνολογικό Πανεπιστήμιο Μέσης Ανατολής',
                dep: 'Επιχειρηματικότητα',
                notes: 'Άγκυρα, 2008',
            },
            {
                name: 'Πανεπιστήμιο Ozyegin',
                dep: 'Επιχειρηματικότητα',
                notes: 'Κωνσταντινούπολη, 2007',
            },
        ],
        languagesTitle: 'Γλώσσες',
        languages: [
            {
                label: 'Αγγλικά',
                rank: "1",
            },
            {
                label: 'Τουρκικά',
                rank: "0",
            },
            {
                label: 'Γερμανικά',
                rank: "3",
            }
        ],
        languageRanks: ["Μητρική", "Άπταιστη", "Ενδιάμεση", "Αρχάρια",],
        privateTitle: 'Ιδιωτική Ζωή',
        private: [
            'Οδηγός υπερκινητήρων μοτοσικλετών',
            'Κατασκήνωση και εργασία από απόσταση με πλήρως εξοπλισμένο και διαδικτυακό καραβάνι',
            'Μαγείρεμα',
            'Πειράματα και συνεισφορές σε ανοικτό κώδικα',
        ]
    },
});